### ISSUE TITLE
Update apps Thrift dependencies to `apache/thrift@0.19`

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/bridget#127]
We introduced a `union` type in #111 but this doesn't get serialised correctly in `swift`. A proof of concept shows that this issue is resolved by serialising with Thrift 0.19.

To support this, and to keep things up to date, we should bring all the apps Thrift dependencies in line to use Thrift 0.19, which includes generating the Bridget models with our `french-thrift` fork of Thrift 0.19.

## Release process

Merge these in order, following the release process in each PR description.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/french-thrift/pull/13
- [ ] https://github.com/guardian/thrift-swift/pull/7
- [ ] https://github.com/guardian/bridget-swift/pull/10
- [ ] https://github.com/guardian/bridget/pull/128
- [ ] https://github.com/guardian/ophan-thrift-swift/pull/11
- [ ] https://github.com/guardian/bridget/issues/138
```

### Current

```mermaid
flowchart TD
    BS(gu/bridget-swift)
    B(gu/bridget)
    ST(gu/thrift-swift@0.14.0-gu6)
    FT(gu/french-thrift@0.14.0-gu6)
    AT(apache/thrift@0.14)
    OTS(gu/ophan-thrift-swift)
    iOS --Depends on--> BS
    iOS --Depends on--> OTS
    OTS --Depends on-->ST
    BS --Depends on--> ST
    ST --Depends on--> FT
    FT --Forks-->AT
    BS --Generated by-->B
    B --Depends on-->FT
```

### Goal

```mermaid
flowchart TD
    BS(gu/bridget-swift)
    B(gu/bridget)
    ST(gu/thrift-swift@0.19.0-gu1)
    FT(gu/french-thrift@0.19.0-gu1)
    AT(apache/thrift@0.19)
    OTS(gu/ophan-thrift-swift)
    iOS --Depends on--> BS
    iOS --Depends on--> OTS
    OTS --Depends on-->ST
    BS --Depends on--> ST
    ST --Depends on--> FT
    FT --Forks-->AT
    BS --Generated by-->B
    B --Depends on-->FT
```

### Why is `ophan-thrift-swift` in this batch of changes?

We need to bump `ophan-thrift-swift` as well because it depends on `guardian/thrift-swift`. If `ophan-thrift-swift` depends on a different version of `thrift-swift` to `bridget-swift` (🤯), Swift package manager can't resolve the versions. The following dependency graph is impossible:

```mermaid
flowchart TD
    BS(gu/bridget-swift)
    B(gu/bridget)
    ST(gu/swift-thrift@0.19)
    FT(gu/french-thrift@0.19)
    AT(apache/thrift@0.19)
    OTS(gu/ophan-thrift-swift)
    STO(gu/swift-thrift@0.14)
    FTO(gu/french-thrift@0.14)
    ATO(apache/thrift@0.14)
    iOS --Depends on--> BS
    iOS --Depends on--> OTS
    OTS --Depends on-->STO
    STO --Depends on-->FTO
    FTO --Forks-->ATO
    BS --Depends on--> ST
    ST --Depends on--> FT
    FT --Forks-->AT
    BS --Generated by-->B
    B --Depends on-->FT

```
